web:
  restart: always
  build: .
  command: npm start
  links:
   - db
  ports:
   - "80:3000"
   - "5858:5858"
   - "35729:35729"
  environment:
   - NODE_ENV=development
  volumes:
   - ./:/opt/mean.js
   - /opt/mean.js/node_modules
   - /opt/mean.js/public
   - /opt/mean.js/uploads
db:
  restart: always
  image: mongo:3.2
  ports:
   - "27017:27017"
  volumes:
   - db:/data/db
